name: Chained
on:
  workflow_run:
    workflows: [Manual trigger]

jobs:

  log-ref-name:
    runs-on: ubuntu-latest
    steps:
      - name: Log GITHUB_REF_NAME
        run: echo "$GITHUB_REF_NAME"
        shell: bash

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Git show
        run: git show
        shell: bash

