name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      fruit:
        type: choice
        options:
          - apple
          - banana

jobs:

  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello, world
        run: echo "Hello, world"
        shell: bash

  inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Inputs
        run: |
          echo "Workflow input is ${{ inputs.fruit }}"
          echo "Job environment variable FRUIT=$FRUIT"
        shell: bash
        env:
          FRUIT: ${{ inputs.fruit || 'coconut' }}

  kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Kotlin script
        run: scripts/hello-world.kts
        shell: bash
