name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      fruit:
        type: choice
        options:
          - apple
          - banana

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello, world
        run: echo "Hello, world"
        shell: bash
  inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Inputs
        run: |
          echo "Workflow input is ${{ inputs.fruit }}"
          echo "Job environment variable FRUIT=$FRUIT"
        shell: bash
        env:
          FRUIT: ${{ inputs.fruit || 'coconut' }}
  kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: Kotlin script
        run: kotlin scripts/hello-world.kts
        shell: bash
